[package]
name = "md_to_svg"
version = "0.2.0"
edition = "2024"
description = "Highly configurable CLI tool to translate Markdown Documents into SVG files."
authors = ["Noah Price: nprice@pricemail.ca"]
repository = "https://github.com/noahprice-dev/md-to-svg"


[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
config = {version ="0.15.19", features=["toml"]}
cosmic-text = "0.17.1"
dirs = "6.0.0"
markdown = "1.0.0"
regex = "1.12.3"
roxmltree = "0.21.1"
serde = {version="1.0.228", features = ["derive"]}
thiserror = "2.0.18"
toml = {version="1.0.6", features=["parse", "serde"]}

[dev-dependencies]
pretty_assertions = "1.4"
