[canvas]
width = 19200
height = 1280
bg_color = "#02b4cc"
# String value that represents the padding around the SVG Text.
# Uses CSS-style padding: "10" (all), "10 20" (vertical, horizontal), "10 20 30" (top, horizontal, bottom) or "10 20 10 20" (top right bottom left)
padding = "0 10 20 30"

[typography]
font_size = 32

# Spacing between lines within a paragraph
line_spacing_factor = 1.5
# Spacing between two discrete paragraphs/blocks
paragraph_spacing_factor = 1.2

# 'Bullet' indentation in em units.
bullet_indent_em = 2

# String value to use as 'bullet' for unordered lists.
bullet_char = ">"

# Optionally disable indenting the first bullet of a list
first_bullet_indent = true

[headers]
# Margin between the top and bottom of Headers.
header_margin_top = 50
header_margin_bot = 50

# Header font-size scales for each rank. 
# e.g. if you have a font size of 16, an h1 (# Header) will have a font size of 24px
[headers.header_scales]
h1 = 2.0
h2 = 1.8
h3 = 1.5
h4 = 1.3
h5 = 1.0
h6 = 0.8
